[nixPacks]
providers = ["python"]

[nixPacks.phases.setup]
nixPkgs = ["python312", "poetry"]

[nixPacks.phases.install]
cmds = ["cd backend && poetry install --no-dev"]

[nixPacks.phases.build]
cmds = ["cd backend && echo 'Build complete'"]

[start]
cmd = "cd backend && poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT"
