services:
  # Backend API Service
  - type: web
    name: is-it-rain-api
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install poetry && cd backend && poetry install --only main
    startCommand: cd backend && poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ALLOWED_ORIGINS
        value: https://is-it-rain.onrender.com,http://localhost:5173
      - key: DATABASE_URL
        value: sqlite:///./data/forecasts.db
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: is-it-rain-frontend
    runtime: static
    region: singapore
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        generateValue: true
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    autoDeploy: true
